New func, tests and docs
speedy93/presence-analyzer-dwysocki pull request #2
Opened 2017-04-10 10:36 UTC by speedy93

![image](https://cloud.githubusercontent.com/assets/18440606/24857876/19123dd8-1dea-11e7-8a5f-cbea626b3f18.png)

![image](https://cloud.githubusercontent.com/assets/18440606/24857918/3e1367ec-1dea-11e7-8dc2-110d0903e521.png)

https://kindergarten.stxnext.pl/browse/WDP-118

2017-04-10 10:44 UTC, dpolcyn commented on src/presence_analyzer/static/presence_start_end.html
> +                                ["Mon", new Date(Date.parse("1,1,1,"+resul["Monday"]["start"])),
????

2017-04-10 10:45 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +                u'Tuesday': {
```from __future__ import unicode_literals```

2017-04-10 10:45 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    seconds_since_midnight)
style

2017-04-10 10:47 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +                    data[user_id][item]['end'])))
style, ) in next line

2017-04-10 10:48 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +            })
style

2017-04-10 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/presence_weekday.html
> +
delete please

2017-04-10 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/mean_time_weekday.html
> +
too many empty lines

2017-04-10 10:51 UTC, speedy93 commented on src/presence_analyzer/static/presence_start_end.html
> +                                ["Mon", new Date(Date.parse("1,1,1,"+resul["Monday"]["start"])),
i dont know what you mean

2017-04-10 10:53 UTC, dpolcyn commented on src/presence_analyzer/static/presence_start_end.html
> +                            function(resul){
) { - space between

2017-04-10 10:53 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        data = dict(json.loads(bad_resp.data))
I don' think  so change for dict is required

2017-04-10 10:54 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +
Without empty line

2017-04-10 10:54 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    resul = {}
result

2017-04-10 10:58 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    for item in data[user_id]:
It wont return full days list of week if someone wasn't working full week. Display all days even if there wasnt any entries

2017-04-11 05:51 UTC, piotrgrundas requested changes

2017-04-11 05:51 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +from utils import seconds_since_midnight  # pylint: disable=relative-import
from x import (
        a, 
        b
    )

2017-04-11 05:51 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        )
str(
        timedelta(seconds=seconds_since_midnight(
            data[user_id][item]['end']
        ))
    )

2017-04-11 05:51 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        result[day] = {'start': '0:0:0', 'end': '0:0:0'}
U don't need to cast it to list.
Use dict comprehension directly insted of this.

2017-04-11 05:51 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                ]
This is wrong
1) create some helper for processing this data,
2) ur passing from the api all 7 days but using here only 5? So pass 5 and just loop over them here
2) in js use singlequotes,

2017-04-11 05:52 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                ]
Also it would be a good idea to move all calculations to some util function to not to mess in the view - it should stay as clean as possible.

2017-04-11 05:55 UTC, piotrgrundas requested changes

2017-04-11 05:55 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        )
Also it would be a good idea to move all calculations to some util function to not to mess in the view - it should stay as clean as possible.

2017-04-11 08:21 UTC, piotrgrundas requested changes

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        for day in list(calendar.day_abbr)[:5]
I've wrote comment about it previously

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        except KeyError as e:  # exception for sunday and saturday
Use continue for this purpose

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                var final_result = [];
1 var, js variables, funct etc names should be camelCase

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                var days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];
This already comes from backend

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                            function(result) {
style

2017-04-11 08:21 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                        $.getJSON("/api/v1/presence_start_end/"+selected_user,
`" + sel`

2017-04-11 08:34 UTC, piotrgrundas requested changes

2017-04-11 08:34 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
>      <style type="text/css">
move styles to separate css file

2017-04-11 09:06 UTC, piotrgrundas requested changes

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +
remove

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +}
enter after each `]`

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +
?

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +    border: 1px solid black;
hex

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +    background: #eee;
uppercase

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/static/mean_time_weekday.html
> +    <link href="/static/css/normalize.css" media="all" rel="stylesheet" type="text/css" />
indent

2017-04-11 09:06 UTC, piotrgrundas requested changes

2017-04-11 09:06 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +            continue
Not like this.

2017-04-11 09:27 UTC, piotrgrundas requested changes

2017-04-11 09:27 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +            result[calendar.day_abbr[item.weekday()]]['end'] = average_time(
this should be a var `calendar.day_abbr[item.weekday()]`

2017-04-12 08:29 UTC, piotrgrundas requested changes

2017-04-12 08:29 UTC, piotrgrundas commented on src/presence_analyzer/static/css/main.css
> +    color: #000000;
`#000000 === #000` Remember it

2017-04-12 08:29 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                            function(result) {
$.getJSON("/api/v1/presence_start_end/" + selected_user, function(result) {

2017-04-12 08:29 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                var days = Object.keys(result);
1 var

2017-04-12 08:38 UTC, piotrgrundas requested changes

2017-04-12 08:38 UTC, piotrgrundas commented on src/presence_analyzer/static/presence_start_end.html
> +                                $.each( days, function(i) {
$.each(days, function(i, day) and adjust rest

2017-04-12 11:48 UTC, merged