WPD-126
speedy93/presence-analyzer-dwysocki pull request #5
Opened 2017-04-18 08:32 UTC by speedy93

![image](https://cloud.githubusercontent.com/assets/18440606/25120535/d7fb51a0-241e-11e7-9901-f1ec3604e5f6.png)

![image](https://cloud.githubusercontent.com/assets/18440606/25120544/e312805e-241e-11e7-94c9-eede07f54875.png)

https://kindergarten.stxnext.pl/browse/WDP-126

2017-04-18 08:52 UTC, piotrgrundas requested changes

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +
remove

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +
remove

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +    {% block body %}  {% endblock %}
`{% block body %}{% endblock %}`

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +    {% block title %} {% endblock %}
remove space between

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/mean_time_weekday.html
> +{% endblock %}
This body is repeated in every template.

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/templates/mean_time_weekday.html
> +                <li><a href="/presence_start_end.html">Presence start-end</a></li>
Do it in a loop in one place.

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    return render_template(template)
And what if template does not exists?

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    print url_for('mean_time_weekday_view', user_id=user_id)
?

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    return result
Why for? Dont assign it if its used only once.

2017-04-18 08:52 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    autoescape=select_autoescape(['html', 'xml'])
xml?

You could use a simple dict for it too.

2017-04-18 13:50 UTC, piotrgrundas requested changes

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    except Exception:
U shouldn't catch generic exception. find out what exception is thrown when there's no such template.

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_start_end.html
> +    {% block title %}<title>Presence analyzer</title>{% endblock %}
`<title>` shouldn't be wrapped in this block. No need for repeating this in all templates.

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_start_end.html
> +{% extends "base.html" %}
enter between blocks in all templates.

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                <h2>{{name}}</h2>
`{{ name }}`
Indent

Wont be easier to send current pair in context to the template and just apply it here and in generating menu items and adding active class? You're repeating this loop.

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                {%- if link == '/'+request.url.rsplit('/', 1)[1] -%}
What for you need to add this leading slash?
Do it without additional  param in rsplit, it's not needed, and select the last element, no the second one.
And that if should only add the class, not generate the whole `<li>`.

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +            {%- endfor -%}
indent

2017-04-18 13:50 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                <li><a href="{{link}}">{{name}}</a></li>
indent

2017-04-20 05:42 UTC, piotrgrundas requested changes

2017-04-20 05:42 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_weekday.html
> +    {% block title %}Presence analyzer{% endblock %}
I don't see the difference between those.

2017-04-20 05:48 UTC, piotrgrundas requested changes

2017-04-20 05:48 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                    {%- if link == request.url.rsplit('/')[-1] -%}
Why not pass the current template and title so you could check it here

2017-04-20 05:48 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                        <li id="selected">
Only `id="selected"` differs.

2017-04-20 05:48 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +                        <a href="{{link}}">{{name}}</a></li>
There was a comment already about it, READ IT!

2017-04-20 07:31 UTC, dpolcyn commented on buildout.cfg
> +
???

2017-04-20 07:31 UTC, dpolcyn commented on mean_time.js
> +                            chart = new google.visualization.ColumnChart($chartDiv[0]);
multiple variable declaration :+1:

2017-04-20 07:32 UTC, dpolcyn commented on src/presence_analyzer/templates/base.html
> +
To many empty lines

2017-04-20 07:33 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +
Without empty line here

2017-04-20 07:33 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +
ditto

2017-04-20 08:08 UTC, dpolcyn commented on src/presence_analyzer/tests.py
>          self.assertEqual(
Style

2017-04-20 08:28 UTC, merged