WPD-135
speedy93/presence-analyzer-dwysocki pull request #7
Opened 2017-04-24 10:15 UTC by speedy93

![image](https://cloud.githubusercontent.com/assets/18440606/25332690/b5141370-28e7-11e7-8913-aa90a18aa445.png)

![image](https://cloud.githubusercontent.com/assets/18440606/25332703/be928e54-28e7-11e7-8dba-1cfff6fc8213.png)

https://kindergarten.stxnext.pl/browse/WDP-135

2017-04-24 10:24 UTC, dpolcyn commented on get_xml.py
> +        export.close()
you don't have to close, thats what with does

2017-04-24 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/js/mean_time.js
> +                $newImg.src = "http://" + result["avatar"];
You should get it from xml file. There is header config.

2017-04-24 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/js/mean_time.js
> +                        console.log("ok");
ok? ok what?

2017-04-24 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/js/mean_time.js
> +
??

2017-04-24 10:50 UTC, dpolcyn commented on src/presence_analyzer/static/js/mean_time.js
> +
???

2017-04-24 10:51 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +                u'user_id': u'176',
unicode

2017-04-24 10:52 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +import xml.etree.ElementTree as ET
I don't see sense of calling it 'ET'

2017-04-24 10:53 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +            data[idx] = {
```
data[user.attrib['id']] = {
    'name': user.find('name').text,
    'avatar': formatted_link_from_xml_here
}
```

2017-04-25 09:50 UTC, piotrgrundas requested changes

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                var $_img = document.getElementById("avatar");
Use `jQueury` since ur using it in every other place, 

`$img = $('#avatar', {src: result['avatar']);`

Also this part gets repeated. Make it reusable.

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                    });
Why? I don't understand of sending call to the same api twice (41, 51). $.getJSON returns a promise on which u can catch fail. Check jQuery docs

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                            hAxis: {title: "Weekday"}
Why? js single quotes, html double.

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                        formatter = new google.visualization.DateFormat({pattern: "HH:mm:ss"}),
ლ(•_•ლ)

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                    data.addColumn("datetime", "Mean time (h:m:s)");
ლ(•_•ლ)

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/start_end.js
> +                fetch("/api/v1/mean_time_weekday/" + $selectedUser)
![image](https://cloud.githubusercontent.com/assets/5078402/25379114/3f2371ea-29ac-11e7-9f23-51f7cfd7a1aa.png)
![image](https://cloud.githubusercontent.com/assets/5078402/25379124/44534334-29ac-11e7-97ab-d9166f0abf35.png)
Why?

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/static/js/weekday.js
> +                    fetch("/api/v1/mean_time_weekday/" + $selectedUser)
Why?

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +    def test_api_avatars(self):
`test_avatars_api`

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +import xml.etree.ElementTree
`from x import ElementTree`

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +        root = xml.etree.ElementTree.parse(xmlfile).getroot()
`ElementTree. ...`

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +            result = '{0}://{1}'.format(
U don't need 0, 1. Just to let u know.

2017-04-25 09:50 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +        }
style

2017-04-26 06:03 UTC, piotrgrundas approved these changes

2017-04-26 06:03 UTC, piotrgrundas commented on get_xml.py
> +    contents = s.read()
s? Make it more descriptive.

2017-04-26 06:03 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                $dropdown.append($('<option />').val(this.user_id).text(this.name));
It's ok, but this is better:
    
    $dropdown.append(
        $('<option />', {
            'val': this.user_id,
            'text': this.name
        })
    );

2017-04-26 06:03 UTC, piotrgrundas commented on src/presence_analyzer/static/js/mean_time.js
> +                $img = $('#avatar').attr('src', result['avatar']);
$('#avatar', {'src', result['avatar']});

Do u use `$img` elsewhere?

2017-04-26 06:03 UTC, piotrgrundas commented on src/presence_analyzer/static/js/start_end.js
> +                    $img = $('#avatar').attr('src', result['avatar']);
Same situation.

2017-04-26 06:03 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        for idx, name in data.items()
`.iteritems()`

2017-04-26 06:32 UTC, merged