Wpd 146
speedy93/presence-analyzer-dwysocki pull request #9
Opened 2017-04-29 08:04 UTC by speedy93

![image](https://cloud.githubusercontent.com/assets/18440606/25554011/28caf836-2cc3-11e7-9df4-e13a9766df9f.png)

![image](https://cloud.githubusercontent.com/assets/18440606/25554014/31f7579c-2cc3-11e7-946d-947cf847fb5d.png)

https://kindergarten.stxnext.pl/browse/WDP-146

2017-05-05 07:25 UTC, piotrgrundas requested changes

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/static/js/overtime.js
> +            $chartDiv.show();
indent

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/static/js/overtime.js
> +                    (day+1).toString(),
space around `+`

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/static/js/overtime.js
> +                    new Date(0,0,0,0,0,0),
ditto

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +            pass
enter

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/templates/overtime.html
> +    </%block>
???

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +            if overtime > 28800:
28800 store this in a descriptive var

2017-05-05 07:25 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +        for item in data[user]:
1 loop!

2017-05-08 05:07 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +            if overtime > 28800:
Why 28800?

2017-05-08 05:42 UTC, dpolcyn commented on src/presence_analyzer/static/js/overtime.js
> +                    (day+1).toString(),
why you sum this here?

2017-05-08 05:42 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +
delete

2017-05-08 05:43 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    return get_overtime(data)
return get_overtime(get_data())

2017-05-08 12:58 UTC, piotrgrundas requested changes

2017-05-08 12:58 UTC, piotrgrundas commented on src/presence_analyzer/static/js/overtime.js
> +                $chartDiv.show();
?

2017-05-08 12:58 UTC, piotrgrundas commented on src/presence_analyzer/templates/mean_time_weekday.html
> +    </% block >
? Stick to one convention

2017-05-08 12:59 UTC, piotrgrundas commented
Correct previous comments

2017-05-09 06:36 UTC, dpolcyn commented on src/presence_analyzer/static/js/overtime.js
> +
remove

2017-05-09 06:37 UTC, dpolcyn commented on src/presence_analyzer/static/js/overtime.js
> +            .fail(function() {
check indent, not sure

2017-05-09 06:37 UTC, dpolcyn commented on src/presence_analyzer/templates/mean_time_weekday.html
> +    </% block >
:+1:

2017-05-09 06:40 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +    ]) * eight_hour
make no sense, multiple it by 28800 or move it to settings and call 'working_hours'

2017-05-09 06:41 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +    eight_hour = 28800
this isn't clear if u don't check if it is 8 hours, no comment etc... 
thats how you should decrare it:
xxx = 60*60*8

2017-05-09 06:42 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +    result = {}
im not sure if you need 2 dicts here to make this, try using one

2017-05-09 09:17 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(
read again pep8 rules, I think u don't understand it yet

2017-05-09 09:19 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +    return sorted(
Won't work properly

2017-05-09 09:53 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    """Return average time when user start the work and when user end the work.
Now is wrong

2017-05-09 09:53 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    """Return average time when user start the work and when user end the work.
Just go with 
"""
xxx
"""

2017-05-09 19:46 UTC, piotrgrundas requested changes

2017-05-09 19:46 UTC, piotrgrundas commented on src/presence_analyzer/templates/overtime.html
> +    </%block>
Really? Bocks shouldn't be indend! It's content should be!

2017-05-09 19:46 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +        1 for x in range(1, date.day)
`xrange`

2017-05-09 19:46 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +
remove

2017-05-09 19:46 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +                result.setdefault(user, {})[year_month] = {'overtime': []}
Why not just
`result[user] = {year_month: {'overtime': []}}`

2017-05-10 07:19 UTC, piotrgrundas requested changes

2017-05-10 07:19 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +    return str(timedelta(seconds=mean(data[board]))).split(".")[0]
`'`
IMO previous version was more readable

2017-05-10 09:11 UTC, merged